spring:
  application:
    name: swe-d2cc-runner
  rabbitmq:
    host: localhost
    port: 5672
    username: gridcapa
    password: gridcapa
    template:
      reply-timeout: 7200000
  cloud:
    stream:
      function:
        definition: request;interrupt
      default:
        binder: rabbit
      bindings:
        interrupt-in-0:
          destination: swe-d2cc-stop-task
        request-in-0:
          destination: swe-d2cc-request
          group: swe-d2cc-runner
        request-out-0:
          destination: swe-d2cc-response
        task-status-update:
          destination: swe-d2cc-task-status-updated
        stop-rao:
          destination: stop-rao-runner

logback:
  amqp:
    exchange: swe-d2cc-task-manager-logs-exchange
    routing-key: "#"

swe-commons:
  zone-id: "Europe/Paris"
  shift-max-iteration-number: 20
  modeling-authority-set:
    REE: "http://www.ree.es/OperationalPlanning"
    REN: "http://www.ren.pt/OperationalPlanning"
    RTEFRANCE: "http://www.rte-france.com/OperationalPlanning"
    SV: "http://www.coreso.eu/OperationalPlanning"

swe-runner:
  dichotomy:
    parameters:
      ES_FR:
        min-value: 0
        max-value: 6400
        precision: 50
        tolerance-Es-Fr: 10
        tolerance-Es-Pt: 50
      FR_ES:
        min-value: 0
        max-value: 6400
        precision: 50
        tolerance-Es-Fr: 10
        tolerance-Es-Pt: 50
      ES_PT:
        min-value: 0
        max-value: 6400
        precision: 50
        tolerance-Es-Fr: 50
        tolerance-Es-Pt: 10
      PT_ES:
        min-value: 0
        max-value: 6400
        precision: 50
        tolerance-Es-Fr: 50
        tolerance-Es-Pt: 10
  whitelist:
    - http://localhost:9000/
    - http://minio:9000/
    - file:/

rao-runner-server:
  amqp:
    client-app-id: swe-runner
    queue-name: rao-request-queue

minio-adapter:
  bucket: gridcapa
  base-path: /SWE/D2CC
  access-key: gridcapa
  secret-key: gridcapa
  url: http://localhost:9000