spring:
  cloud:
    function:
      definition: request;softInterrupt

swe-commons:
  zone-id: "Europe/Paris"
  shift-max-iteration-number: 30
  modeling-authority-map:
    REE: "http://www.ree.es/OperationalPlanning"
    REN: "http://www.ren.pt/OperationalPlanning"
    RTEFRANCE: "http://www.rte-france.com/OperationalPlanning"
    SV: "http://www.coreso.eu/OperationalPlanning"

swe-runner:
  dichotomy:
    parameters:
      ES_FR:
        tolerance-Es-Fr: 10
        tolerance-Es-Pt: 50
      FR_ES:
        tolerance-Es-Fr: 10
        tolerance-Es-Pt: 50
      ES_PT:
        tolerance-Es-Fr: 50
        tolerance-Es-Pt: 10
      PT_ES:
        tolerance-Es-Fr: 50
        tolerance-Es-Pt: 10
  export-failed-network: false