spring:
  application:
    name: swe-d2cc-runner
  rabbitmq:
    host: localhost
    port: 5672
    username: gridcapa
    password: gridcapa
    template:
      reply-timeout: 7200000
  cloud:
    function:
      definition: request;softInterrupt;consumeTaskDtoUpdate
    stream:
      default:
        binder: rabbit
      bindings:
        softInterrupt-in-0:
          destination: swe-d2cc-stop-task
        request-in-0:
          destination: swe-d2cc-request
          group: swe-d2cc-runner
        request-out-0:
          destination: swe-d2cc-response
        task-status-update:
          destination: swe-d2cc-task-status-updated
        stop-rao:
          destination: stop-rao-runner
        consumeTaskDtoUpdate-in-0:
          destination: swe-d2cc-task-updated
      rabbit:
        default:
          consumer:
            auto-bind-dlq: true
            max-attempts: 1
        bindings:
          consumeTaskDtoUpdate-in-0:
            consumer:
              binding-routing-key: status

logback:
  amqp:
    exchange: swe-d2cc-task-manager-logs-exchange
    routing-key: "#"

swe-commons:
  zone-id: "Europe/Paris"
  shift-max-iteration-number: 20
  modeling-authority-map:
    REE: "http://www.ree.es/OperationalPlanning"
    REN: "http://www.ren.pt/OperationalPlanning"
    RTEFRANCE: "http://www.rte-france.com/OperationalPlanning"
    SV: "http://www.coreso.eu/OperationalPlanning"

swe-runner:
  pst:
    pst-ids:
      - _e071a1d4-fef5-1bd9-5278-d195c5597b6e
      - _7824bc48-fc86-51db-8f9c-01b44933839e
      - _f82152ac-578e-500e-97db-84e788c471ee
  unoptimized-cnecs-with-pst-es-fr:
    active : false
  dichotomy:
    parameters:
      ES_FR:
        tolerance-Es-Fr: 10
        tolerance-Es-Pt: 50
      FR_ES:
        tolerance-Es-Fr: 10
        tolerance-Es-Pt: 50
      ES_PT:
        tolerance-Es-Fr: 50
        tolerance-Es-Pt: 10
      PT_ES:
        tolerance-Es-Fr: 50
        tolerance-Es-Pt: 10
  whitelist:
    - http://localhost:9000/
    - http://minio:9000/
    - file:/

rao-runner-server:
  amqp:
    client-app-id: swe-runner
    queue-name: rao-request-queue

minio-adapter:
  bucket: gridcapa
  base-path: /SWE/D2CC
  access-key: gridcapa
  secret-key: gridcapa
  url: http://localhost:9000

ftp:
  host: localhost
  port: 21
  access-key: gridcapa
  secret-key: gridcapa
  remote-relative-destination-directory: swe/d2cc/outputs
  retry-count: 3
  retry-sleep: 5

task-manager:
  base-url: http://localhost/swe/d2cc/task-manager
  fetch-task:
    retries-number: 6
    interval-in-seconds: 10